#!/usr/bin/env ruby

require 'rbbt-util'
require 'rbbt/util/simpleopt'


file = ARGV.shift
identifiers = ARGV.shift
format = ARGV.shift

file = STDIN if file == '-'

puts TSV.open(file).attach identifiers, :fields => [format]

