#!/usr/bin/env ruby

require 'rbbt-util'
require 'rbbt/util/simpleopt'
require 'rbbt/sources/organism'

options = SOPT.get("-f--file* File to process:-f--field* Field to change:-t--target* Target format:-i--identifiers* Identifier file to use")

raise ParameterException, "No file given" unless file = options[:file]
raise ParameterException, "No field given" unless field = options[:field]
raise ParameterException, "No target given" unless target = options[:target]

identifiers = options[:identifiers] || Organism.identifiers("Hsa").find

begin
  index = TSV.index(identifiers, :persist => true, :target => target, :merge => true)
rescue
  raise ParameterException, "Could not build index for '#{target}': #{ identifiers }"
end

tsv = TSV.open file

tsv.process field do |value|
  if Array === value
    index.values_at *value
  else
    index[value]
  end
end

tsv.fields = tsv.fields.collect{|f| f == field ? target : f}

puts tsv

exit

#stream = Open.open file
#header = TSV.parse_header stream
#field_pos = header.all_fields.index field
#raise ParameterException, "Unknown field: #{ field }" unless field_pos
#
#out = STDOUT
#out.puts TSV.header_lines :fields => header.fields, :key_field =
#while line = stream.gets do
#  if line =~ /^#/
#    out.puts line
#    next
#  else
#  end
#end
#
