#!/usr/bin/env ruby

require 'rbbt'
require 'highline/import'

if Rbbt.etc.web_users.exists?
  web_users = Rbbt.etc.web_users.yaml
else
  web_users = {}
end

user = ARGV.shift

raise "No user provided" if user.nil?

password = ask("Enter your password:  ") { |q| q.echo = "x" }

raise "No password provided" if password.nil?

password_check = ask("Re-enter your password:  ") { |q| q.echo = "x" }

raise "Passwords don't match" if password != password_check

web_users[user] = password

Rbbt.etc.web_users.write(web_users.to_yaml)
