#!/usr/bin/env ruby

require 'rbbt'


cmd, *rest = ARGV

aliases ||= Rbbt.etc.cmd_alias.exists? ? Rbbt.etc.cmd_alias.yaml : {}

if cmd.nil?
  aliases.each do |name, parts|
    parts = parts.collect{|p|
      p =~ /^[\w:_\/-]*$/ ? p : "'" << p << "'"
    }
    puts [Log.color(:magenta, name), parts * " "] * ": "
  end
  exit 0
end

if rest.empty?
  aliases.delete cmd
else
  aliases[cmd] = rest
end

Open.write(Rbbt.etc.cmd_alias.find,(aliases.to_yaml))

