#!/usr/bin/env ruby

require 'rbbt-util'
require 'rbbt/util/simpleopt'
require 'rbbt/workflow'

$0 = "rbbt #{$previous_commands*""} #{ File.basename(__FILE__) }" if $previous_commands

options = SOPT.setup <<EOF

Remove a job and its dependencies

$ rbbt purge [options] <job_path> 

-h--help Print this help
-r--recursive Remove recursively
EOF
if options[:help]
  if defined? rbbt_usage
    rbbt_usage 
  else
    puts SOPT.doc
  end
  exit 0
end

path, search_path, _sep, *other = ARGV

raise ParameterException, "No path given" if path.nil? 

Step.purge(path, options[:recursive])
