#!/usr/bin/env ruby

require 'rbbt'

resource = ARGV.first

config_file = Rbbt.etc.file_servers

file_servers = config_file.exists? ? config_file.yaml : {}
file_servers.delete resource
Open.write(config_file.find(:user), file_servers.to_yaml)

