#!/usr/bin/env ruby

require 'rbbt/workflow'

require 'rbbt-util'
require 'fileutils'
require 'rbbt/util/simpleopt'
require 'rbbt/workflow/step'
require 'rbbt/util/misc'

require 'rbbt-util'
require 'rbbt/util/simpleopt'

$0 = "rbbt #{$previous_commands*""} #{ File.basename(__FILE__) }" if $previous_commands

options = SOPT.setup <<EOF
Examine the provenance of a job result

$ rbbt workflow archive <target> <job> [<job> ...]

Archive jobs and all dependencies into the target tar gz file or directory. If no target is specified 
it defaults to a <job>.tar.gz

-h--help Help
EOF

SOPT.usage if options[:help]

target, *files = ARGV

raise "Target already exists: #{ target }" if File.exists?(target) and not File.directory?(target)
Step.archive(files, target)
