#!/usr/bin/env ruby

require 'rbbt/workflow'

require 'rbbt-util'
require 'rbbt-util'
require 'rbbt/util/simpleopt'

$0 = "rbbt #{$previous_commands*""} #{ File.basename(__FILE__) }" if $previous_commands

options = SOPT.setup <<EOF
Examine the info of a job result

$ rbbt workflow info <job-result>

-h--help Help
-a--all Print all info entries
-r--recursive Print recursive input values
-o--original Print original object
EOF

SOPT.usage if options[:help]

file = ARGV.shift
all = options.delete :all
recursive = options.delete :recursive

def get_step(file)
  file = file.sub(/\.(info|files)/,'')
  step = Workflow.load_step file
  step
end

def status_msg(status)
  color = case status.to_sym
          when :error, :aborted, :missing, :dead
            :red
          when :streaming, :started
            :cyan
          when :done
            :green
          when :noinfo
            :blue
          when :dependencies, :waiting, :setyp
            :yellow
          else
            if status.to_s.index ">"
              :cyan
            else
              :cyan
            end
          end
  Log.color(color, status.to_s)
end

def pid_msg(pid, done = false)
  color = if pid and (done or Misc.pid_exists? pid)
            :green
          else
            :red
          end
  if pid.nil?
    ""
  else
    Log.color(color, pid)
  end
end

step = get_step file

info = step.info

if options[:original]
  puts info.inspect
  exit 0
end

dependencies = info[:dependencies]
inputs = info[:inputs]
status = info[:status]
time = info[:time_elapsed]
total_time = info[:total_time_elapsed]
messages = info[:messages]
backtrace = info[:backtrace]
pid = info[:pid]
exception = info[:exception]
rest = info.keys - [:inputs, :dependencies, :status, :time_elapsed, :messages, :backtrace, :exception, :pid, :archived_info]

puts Log.color(:magenta, "File") << ": " << step.path
puts Log.color(:magenta, "Status") << ": " << status_msg(status) << ((step.aborted? || step.error?) && step.recoverable_error? ? " (recoverable)" : "" ) << (step.dirty? ? " (dirty)" : "")
puts Log.color(:magenta, "Pid") << ": " << pid_msg(pid, status.to_s == "done")
puts Log.color(:magenta, "Time") << ": " << time.to_i.to_s << " sec." if time
puts Log.color(:magenta, "Total time") << ": " << total_time.to_i.to_s << " sec." if time
if inputs and inputs.any?
  puts Log.color(:magenta, "Inputs")
  inputs.each do |input,value|
    case value
    when nil
      puts Misc.format_definition_list_item("  " + input.to_s, 'nil', 80, 20, :blue)
    when Array
      puts Misc.format_definition_list_item("  " + input.to_s, (value.length > 6 ? value[0..5]*"\n" << "\n" << "..." : value * "\n" ), 80, 20, :blue)
    when TrueClass, FalseClass
      puts Misc.format_definition_list_item("  " + input.to_s, value.to_s, 80, 20, :blue)
    else
      text = value.to_s.split("\n")[0..5].compact * "\n\n"
      puts Misc.format_definition_list_item("  " + input.to_s, text, 80, 20, :blue)
    end
  end
end

if dependencies and dependencies.any?
  puts Log.color(:magenta, "Dependencies") << ": "
  dependencies.each do |name,task,file|
    puts "  " << file
  end 
end

if messages and messages.any?
  puts Log.color(:magenta, "Messages") << ": "
  messages.each do |msg|
    puts "  " << msg
  end 
end

if status != :done && step.file('progress').exists?
  progress = step.file('progress').yaml
  str = Log.color(:magenta, "Progress") << ": " 
  if progress[:last_percent]
    str << progress[:last_percent].to_s << "%"
  else
    str << progress[:ticks].to_s << " items"
  end
  puts str
end

if status == :error
  puts Log.color(:magenta, "Backtrace") << ": "
  puts Log.color_stack backtrace
end

if all
  puts Log.color(:magenta, "Other entries") << ": "
  rest.each do |key|
    puts Misc.format_definition_list_item(key, info[key].to_s)
  end
end

if recursive
  inputs = step.info[:inputs] || {}
  deps = step.dependencies

  while deps.any? do
    dep = deps.shift
    inputs = {} if inputs.nil?
    inputs = inputs.merge(dep.info[:inputs] || {})
    deps = deps.concat dep.dependencies if dep.dependencies
  end

  inputs = inputs.merge step.archived_inputs
  if inputs.any?
    puts Log.color(:magenta, "Recursive inputs") << ": "
    inputs.each do |input,value|
      case value
      when nil
        puts Misc.format_definition_list_item("  " << input.to_s, 'nil', 80, 20, :blue)
      when Array
        puts Misc.format_definition_list_item("  " << input.to_s, (value.length > 6 ? (value[0..5])*"\n\n" << "\n\n" << "..." : value * "\n\n" ), 80, 20, :blue).gsub("\n\n","\n")
      when TrueClass, FalseClass
        puts Misc.format_definition_list_item("  " << input.to_s, value.to_s, 80, 20, :blue)
      else
        lines = value.to_s.split("\n").collect{|l| l.length >= 60 ? l[0..45] + " ..." : l }
        text = lines[0..5].compact * "\n\n"
        text << "\n\n...\n\n" if lines.length > 6
        puts Misc.format_definition_list_item("  " << input.to_s, text, 80, 20, :blue).gsub("\n\n","\n")
      end
    end
  end

end
