#!/usr/bin/env ruby

require 'rbbt-util'
require 'rbbt/workflow'
require 'rbbt/util/simpleopt'

options = SOPT.get('-wd--workflow_dir*:-d--describe')

workflow_dir = options[:workflow_dir] || Workflow.workflow_dir

Path.setup(workflow_dir) unless Path === workflow_dir

workflows = Workflow.installed_workflows

if options[:describe]
  workflows.sort.each do |workflow|
    Workflow.require_workflow workflow
    workflow = Workflow.workflows.select{|w| Misc.camel_case(w.to_s) == Misc.camel_case(workflow)}.first
    puts "# "<<[Misc.camel_case(workflow.to_s), workflow.description] * ": "
    workflow.tasks.each do |name,task|
      puts "  * " << [name, task.inputs * " "] * ": "
    end
    puts

  end
else
  workflows.sort.each do |workflow|
    puts Misc.camel_case(workflow.to_s)
  end
end
